//libraries
import Head from 'next/head'
import { InferGetServerSidePropsType } from 'next'
import axios from 'axios'
//components
import SearchBar from '../components/SearchBar/index'
import CoinList from '../components/CoinList'
//interfaces
import {filteredCoinInterface} from '../interfaces/components/CoinList.interface'



export default function Home({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchBar  type = "text"  placeholder = "Search..."/>
      <CoinList filteredCoins  = {data}/>
    </div>
  )
}



export const getServerSideProps = async () => {
  const {data} : {data : Array<filteredCoinInterface> }  = await axios.get('https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&order=market_cap_desc&per_page=10&page=1&sparkline=false')
  return {
    props: {
      data,
    },
  }
}


